SELECT
	wu.ID,
	wu.user_email,
	wu.user_login,
	wu.user_pass,
	wu.user_nicename,
	wu.user_url,
	wu.user_registered,
	wu.display_name,
	um.meta_value AS permissions,
	um.meta_key
FROM
	wp_users wu
JOIN wp_usermeta um
ON
	um.user_id = wu.ID
WHERE
	um.meta_key = "wp_capabilities"
	AND (
		(um.meta_value LIKE '%author%'
		OR um.meta_value LIKE '%admin%'
		OR (
			um.meta_value LIKE '%customer%'
			AND wu.user_email NOT LIKE "%test.it"
			AND wu.user_email NOT LIKE "%test-%"
			AND wu.user_email NOT LIKE "%testiamo%"
			AND wu.user_email NOT LIKE "%proviamo%"
			AND wu.user_email NOT LIKE "%prova.it"
			AND wu.user_email NOT LIKE "%prova.com"
			AND wu.user_email NOT LIKE "%spam%"
			AND wu.user_email NOT LIKE "%.us"
			AND wu.user_email NOT LIKE "%discardmail%"
			AND wu.user_email NOT LIKE "%.lv"
			AND wu.user_email NOT LIKE "%laposte%"
			AND wu.user_email NOT LIKE "%.ru"
			AND wu.user_email NOT LIKE "%.bid"
			AND wu.user_email NOT LIKE "%ljxvwj.com%"
			AND wu.user_email NOT LIKE "%@katamail%"
			AND wu.user_email NOT LIKE "%adp.com"
			AND wu.user_email NOT LIKE "%sky.com"
			AND wu.user_email NOT LIKE "%bangkok%"
			AND wu.user_email NOT LIKE "%.uk"
			AND wu.user_email NOT LIKE ".ru%"
			AND wu.user_email NOT LIKE "%.in"
			AND wu.user_email NOT REGEXP 'test[0-9]{1,2}'
			AND wu.user_email NOT REGEXP 'test-[0-9]{1,2}'
			))
	OR wu.ID NOT IN (
	SELECT
		wu.ID
	FROM
		wp_users wu
	WHERE
		(
        wu.user_email LIKE "%.ru"
        OR wu.user_email LIKE "%.sg"
        OR wu.user_email LIKE "%thefunones.com"
        OR wu.user_email LIKE "%thefloraculture.com"
        OR wu.user_email LIKE "%live.com"
        OR wu.user_email LIKE "%juno%"
        OR wu.user_email LIKE "%yasm%"
        OR wu.user_email LIKE "%corn%"
        OR wu.user_email LIKE "%steel%"
        OR wu.user_email LIKE "%craft%"
        OR wu.user_email LIKE "%gok%"
        OR wu.user_email LIKE "%whal%"
        OR wu.user_email LIKE "%mail%"
        OR wu.user_email LIKE "%icloud%"
        OR wu.user_email LIKE "%me.com"
        OR wu.user_email LIKE "%tax%"
        OR wu.user_email LIKE "%hotel%"
        OR wu.user_email LIKE "%corp%"
        OR wu.user_email LIKE "%box.com"
        OR wu.user_email LIKE "%ing.com"
        OR wu.user_email LIKE "%machinery%"
        OR wu.user_email LIKE "%lopes.com"
        OR wu.user_email LIKE "%outlook.com"
        OR wu.user_email LIKE "%jadeschoice.com"
        OR wu.user_email LIKE "%amysink.com"
        OR wu.user_email LIKE "%msn.com"
        OR wu.user_email LIKE "%online%"
        OR wu.user_email LIKE "%muskgrow.com"
        OR wu.user_email LIKE "%heartandleg.com"
        OR wu.user_email LIKE "%guest%"
        OR wu.user_email LIKE "%associate%"
		OR wu.user_email LIKE "%forex%"
		OR wu.user_email LIKE "%family%"
		OR wu.user_email LIKE "%.ee"
		OR wu.user_email LIKE "%playworldsystems.com"
		OR wu.user_email LIKE "%laserzone123.com"
		OR wu.user_email LIKE "%spunkymonkeymedia.com"
		OR wu.user_email LIKE "%bob%"
		OR wu.user_email LIKE "%micro%"
        	OR wu.user_email LIKE "%yahoo.com"
        	OR wu.user_email LIKE "%richmond%"
        	OR wu.user_email LIKE "%@hantzmonwiebel.com"
			OR wu.user_email LIKE "%test.it"
			OR wu.user_email LIKE "%proviamo%"
			OR wu.user_email LIKE "%prova.it"
			OR wu.user_email LIKE "%yandex%"
			OR wu.user_email LIKE "%spamavert%"
			OR wu.user_email LIKE "%mailcatch%"
			OR wu.user_email LIKE "%laposte%"
			OR wu.user_email LIKE "%.ua"
			OR wu.user_email LIKE "%yeah.net"
			OR wu.user_email LIKE "%.de"
			OR wu.user_email LIKE "%163.com"
			OR wu.user_email LIKE "%cucinabambini.com"
			OR wu.user_email LIKE "%.club"
			OR wu.user_email LIKE "%.tv"
			OR wu.user_email LIKE "%.ymail.com"
			OR wu.user_email LIKE "%.displaytransactions"
			OR wu.user_email LIKE "%.nl"
			OR wu.user_email LIKE "%.fr"
			OR wu.user_email LIKE "%.pl"
			OR wu.user_email LIKE "%.in"
			OR wu.user_email LIKE "%.biz"
			OR wu.user_email LIKE "%.ca"
			OR wu.user_email LIKE "%getmailsonline.com"
			OR wu.user_email LIKE "%avenue5apt.com"
			OR wu.user_email LIKE "%calzeprestige.com"
			OR wu.user_email LIKE "%btinternet.com"
			OR wu.user_email LIKE "%lumberhardware.com"
			OR wu.user_email LIKE "%bunge.com"
			OR wu.user_email LIKE "%cunadousa.com"
			OR wu.user_email LIKE "%aol.com"
			OR wu.user_email LIKE "%.net"
			OR wu.user_email LIKE "%california%"
			OR wu.user_email LIKE "%market%"
			OR wu.user_email LIKE "%bett%"
			OR wu.user_email LIKE "%.cn%"
			OR wu.user_email LIKE "%milf%"
			OR wu.user_email LIKE "%depot%"
			OR wu.user_email LIKE "%.site"
			OR wu.user_email LIKE "%.online"
			OR wu.user_email LIKE "%maildeviant.com"
			OR wu.user_email LIKE "%.org"
			OR wu.user_email LIKE "%.shop"
			OR wu.user_email LIKE "%.club"
			OR wu.user_email LIKE "%.xyz"
			OR wu.user_email LIKE "%boston%"
			OR wu.user_email LIKE "%.lol"
			OR wu.user_email LIKE "%@gsasearchenginerankerhelp.com"
			OR wu.user_email LIKE "%holdings%"
			OR wu.user_email LIKE "%poker%"
			OR wu.user_email LIKE "%sex%"
			OR wu.user_email LIKE "%help%"
			OR wu.user_email LIKE "%.services"
			OR wu.user_email LIKE "%.co"
			OR wu.user_email LIKE "%.edu"
			OR wu.user_email LIKE "%.tk"
			OR wu.user_email LIKE "%.tw"
			OR wu.user_email LIKE "%.info"
			OR wu.user_email LIKE "%.bz"
			OR wu.user_email LIKE "%.pw"
			OR wu.user_email LIKE "%.website"
			OR wu.user_email LIKE "%capital%"
			OR wu.user_email LIKE "%group%"
			OR wu.user_email LIKE "%.ml"
			OR wu.user_email LIKE "%.party"
			OR wu.user_email LIKE "%.pro"
			OR wu.user_email LIKE "%asia%"
			OR wu.user_email LIKE "%model%"
			OR wu.user_email LIKE "%date%"
			OR wu.user_email LIKE "%.gov"
			OR wu.user_email LIKE "%hosting%"
			OR wu.user_email LIKE "%i.c%"
			OR wu.user_email LIKE "%wa.%"
			OR wu.user_email LIKE "%ic.%"
			OR wu.user_email LIKE "%broker%"
			OR wu.user_email LIKE "%finance%"
			OR wu.user_email LIKE "%jobs%"
			OR wu.user_email LIKE "%privacy%"
			OR wu.user_email LIKE "%inc.com"
			OR wu.user_email LIKE "%.eu"
			OR wu.user_email LIKE "%.ch"
			OR wu.user_email LIKE "%store%"
			OR wu.user_email LIKE "%proxy%"
			OR wu.user_email LIKE "%.cf"
			OR wu.user_email LIKE "%pay%"
			OR wu.user_email LIKE "%law%"
			OR wu.user_email LIKE "%gmx.com"
			OR wu.user_email LIKE "%exnik.com"
			OR wu.user_email LIKE "%.instambox.com"
			OR wu.user_email LIKE "%.ir"
			OR wu.user_email LIKE "%agric%"
			OR wu.user_email LIKE "%.lv"
			OR wu.user_email LIKE "%escort%"
			OR wu.user_email LIKE "%shamroad%"
			OR wu.user_email LIKE "%poet.com"
			OR wu.user_email LIKE "%.icu"
			OR wu.user_email LIKE "%.dk"
			OR wu.user_email LIKE "%bthow.com"
			OR wu.user_email LIKE "%wpgun.com"
			OR wu.user_email LIKE "%vocalmajoritynow.com"
			OR wu.user_email LIKE "%scoldly.com"
			OR wu.user_email LIKE "%warboardplace.com"
			OR wu.user_email LIKE "%mapk.me"
			OR wu.user_email LIKE "%facebook.com"
			OR wu.user_email LIKE "%111%"
			OR wu.user_email LIKE "%qq%"
			OR wu.user_email LIKE "%aaa%"
			OR wu.user_email LIKE "%text.com"
			OR wu.user_email LIKE "%inbox.com"
			OR wu.user_email LIKE "%mail.com"
			OR wu.user_email LIKE "%sons.com"
			OR wu.user_email LIKE "%iews.com"
			OR wu.user_email LIKE "%link%"
			OR wu.user_email LIKE "%dns%"
			OR wu.user_email LIKE "%diamond%"
			OR wu.user_email LIKE "%auto%"
			OR wu.user_email LIKE "%.red"
			OR wu.user_email LIKE "%scp.com"
			OR wu.user_email LIKE "%gnd.com"
			OR wu.user_email LIKE "%dne.com"
			OR wu.user_email LIKE "%ly.com"
			OR wu.user_email LIKE "%.cat"
			OR wu.user_email LIKE "%insurance%"
			OR wu.user_email LIKE "%bike%"
			OR wu.user_email LIKE "%.wine"
			OR wu.user_email LIKE "%guys%"
			OR wu.user_email LIKE "%girls%"
			OR wu.user_email LIKE "%uiscape%"
			OR wu.user_email LIKE "%location%"
			OR wu.user_email LIKE "%coffee%"
			OR wu.user_email LIKE "%sites.com"
			OR wu.user_email LIKE "%novartis%"
			OR wu.user_email LIKE "%salas-%"
			OR wu.user_email LIKE "%.io"
			OR wu.user_email LIKE "%.space"
			OR wu.user_email LIKE "%verified%"
			OR wu.user_email LIKE "%.life"
			OR wu.user_email LIKE "%.se"
			OR wu.user_email LIKE "%.click"
			OR wu.user_email LIKE "%.town"
			OR wu.user_email LIKE "%trans%"
			OR wu.user_email LIKE "%wyoming%"
			OR wu.user_email LIKE "%fn.com"
			OR wu.user_email LIKE "%gja.com"
			OR wu.user_email LIKE "%.beauty"
			OR wu.user_email LIKE "%kellog.com"
			OR wu.user_email LIKE "%ww.com"
			OR wu.user_email LIKE "%cow.com"
			OR wu.user_email LIKE "%-r.com"
			OR wu.user_email LIKE "%.es"
			OR wu.user_email LIKE "%pepsico%"
			OR wu.user_email LIKE "%.top"
			OR wu.user_email LIKE "%scape.com"
			OR wu.user_email LIKE "%.best"
			OR wu.user_email LIKE "%bt.com"
			OR wu.user_email LIKE "%benefit%"
			OR wu.user_email LIKE "%.institute"
			OR wu.user_email LIKE "%photoaim%"
			OR wu.user_email LIKE "%work%"
			OR wu.user_email LIKE "%trade%"
			OR wu.user_email LIKE "%crypto%"
			OR wu.user_email LIKE "%coin%"
			OR wu.user_email LIKE "%.team"
			OR wu.user_email LIKE "%chanel.com"
			OR wu.user_email LIKE "%aim.com"
			OR wu.user_email LIKE "%brunette%"
			OR wu.user_email LIKE "%.tech"
			OR wu.user_email LIKE "%.sk"
			OR wu.user_email LIKE "%.hu"
			OR wu.user_email LIKE "%skincare%"
			OR wu.user_email LIKE "%waiwai%"
			OR wu.user_email LIKE "%free.%"
			OR wu.user_email LIKE "%@free%"
			OR wu.user_email LIKE "%writing%"
			OR wu.user_email LIKE "%.blog"
			OR wu.user_email LIKE "%.dev"
			OR wu.user_email LIKE "%.world"
			OR wu.user_email LIKE "%.agency"
			OR wu.user_email LIKE "%.guru"
			OR wu.user_email LIKE "%.space"
			OR wu.user_email LIKE "%.design"
			OR wu.user_email LIKE "%.info"
			OR wu.user_email LIKE "%.network"
			OR wu.user_email LIKE "%.digital"
			OR wu.user_email LIKE "%.global"
			OR wu.user_email LIKE "%.life"
			OR wu.user_email LIKE "%.media"
			OR wu.user_email LIKE "%.today"
			OR wu.user_email LIKE "%.works"
			OR wu.user_email LIKE "%.zone"
			OR wu.user_email LIKE "%.club"
			OR wu.user_email LIKE "%.codes"
			OR wu.user_email LIKE "%.email"
			OR wu.user_email LIKE "%.expert"
			OR wu.user_email LIKE "%.international"
			OR wu.user_email LIKE "%.school"
			OR wu.user_email LIKE "%.solutions"
			OR wu.user_email LIKE "%.technology"
			OR wu.user_email LIKE "%.center"
			OR wu.user_email LIKE "%.company"
			OR wu.user_email LIKE "%.systems"
			OR wu.user_email LIKE "%.academy"
			OR wu.user_email LIKE "%.management"
			OR wu.user_email LIKE "%.photography"
			OR wu.user_email LIKE "%.services"
			OR wu.user_email LIKE "%.studio"
			OR wu.user_email LIKE "%.tips"
			OR wu.user_email LIKE "%.tools"
			OR wu.user_email LIKE "%.consulting"
			OR wu.user_email LIKE "%.marketing"
			OR wu.user_email LIKE "%.support"
			OR wu.user_email LIKE "%.group"
			OR wu.user_email LIKE "%.enterprises"
			OR wu.user_email LIKE "%.careers"
			OR wu.user_email LIKE "%.voyage"
			OR wu.user_email LIKE "%.builders"
			OR wu.user_email LIKE "%.associates"
			OR wu.user_email LIKE "%.codes"
			OR wu.user_email LIKE "%.digital"
			OR wu.user_email LIKE "%.exchange"
			OR wu.user_email LIKE "%.expert"
			OR wu.user_email LIKE "%.farm"
			OR wu.user_email LIKE "%.marketing"
			OR wu.user_email LIKE "%.sarl"
			OR wu.user_email LIKE "%.reisen"
			OR wu.user_email LIKE "%.town"
			OR wu.user_email LIKE "%.boutique"
			OR wu.user_email LIKE "%.florist"
			OR wu.user_email LIKE "%.rentals"
			OR wu.user_email LIKE "%.photography"
			OR wu.user_email LIKE "%.tienda"
			OR wu.user_email LIKE "%.catering"
			OR wu.user_email LIKE "%.support"
			OR wu.user_email LIKE "%.supply"
			OR wu.user_email LIKE "%.industries"
			OR wu.user_email LIKE "%.properties"
			OR wu.user_email LIKE "%.productions"
			OR wu.user_email LIKE "%.codes"
			OR wu.user_email LIKE "%.ventures"
			OR wu.user_email LIKE "%.holiday"
			OR wu.user_email LIKE "%.voyage"
			OR wu.user_email LIKE "%.pub"
			OR wu.user_email LIKE "%.gift"
			OR wu.user_email LIKE "%.media"
			OR wu.user_email LIKE "%.discount"
			OR wu.user_email LIKE "%.finance"
			OR wu.user_email LIKE "%.productions"
			OR wu.user_email LIKE "%.energy"
			OR wu.user_email LIKE "%.gold"
			OR wu.user_email LIKE "%.diamonds"
			OR wu.user_email LIKE "%.toys"
			OR wu.user_email LIKE "%.tips"
			OR wu.user_email LIKE "%.care"
			OR wu.user_email LIKE "%.exchange"
			OR wu.user_email LIKE "%.exposed"
			OR wu.user_email LIKE "%.cool"
			OR wu.user_email LIKE "%.gripe"
			OR wu.user_email LIKE "%.fail"
			OR wu.user_email LIKE "%.limited"
			OR wu.user_email LIKE "%.careers"
			OR wu.user_email LIKE "%.social"
			OR wu.user_email LIKE "%.wtf"
			OR wu.user_email LIKE "%.world"
			OR wu.user_email LIKE "%.zone"
			OR wu.user_email LIKE "%.farm"
			OR wu.user_email LIKE "%.ai"
			OR wu.user_email LIKE "%concrete%"
			OR wu.user_email LIKE "%enterprise%"
			OR wu.user_email LIKE "%connects%"
			OR wu.user_email LIKE "%consult%"
			OR wu.user_email LIKE "%identity%"
			OR wu.user_email LIKE "%@fort%"
			OR wu.user_email LIKE "%slumber%"
			OR wu.user_email LIKE "%invest%"
			OR wu.user_email LIKE "%west%"
			OR wu.user_email LIKE "%.xom"
			OR wu.user_email LIKE "%.cz"
			OR wu.user_email LIKE "%jean%"
			OR wu.user_email LIKE "%scopelimit.com"
			OR wu.user_email LIKE "%directbox.com"
			OR wu.user_email LIKE "%recover%"
			OR wu.user_email LIKE "%bailey%"
			OR wu.user_email LIKE "%hailey%"
			OR wu.user_email LIKE "%how.com"
			OR wu.user_email LIKE "%funeral%"
			OR wu.user_email LIKE "%psychology%"
			OR wu.user_email LIKE "%jewelry%"
			OR wu.user_email LIKE "%name.com"
			OR wu.user_email LIKE "%accounting%"
			OR wu.user_email LIKE "%online.com"
			OR wu.user_email LIKE "%mgt.com"
			OR wu.user_email LIKE "%plumbing%"
			OR wu.user_email LIKE "%realty%"
			OR wu.user_email LIKE "%schools%"
			OR wu.user_email LIKE "%statefarm.com"
			OR wu.user_email LIKE "%ctte%"
			OR wu.user_email LIKE "%cement%"
			OR wu.user_email LIKE "%comex%"
			OR wu.user_email LIKE "%tins.com"
			OR wu.user_email LIKE "%.gq"
			OR wu.user_email LIKE "%hp.com"
			OR wu.user_email LIKE "%health%"
			OR wu.user_email LIKE "%solutions%"
			OR wu.user_email LIKE "%welcome%"
			OR wu.user_email LIKE "%badoo%"
			OR wu.user_email LIKE "%chile.com"
			OR wu.user_email LIKE "%adorable%"
			OR wu.user_email LIKE "%ambulance%"
			OR wu.user_email LIKE "%jacket%"
			OR wu.user_email LIKE "%angela%"
			OR wu.user_email LIKE "%angelina%"
			OR wu.user_email LIKE "%angelita%"
			OR wu.user_email LIKE "%queen%"
			OR wu.user_email LIKE "%princess%"
			OR wu.user_email LIKE "%annette%"
			OR wu.user_email LIKE "%austin%"
			OR wu.user_email LIKE "%photo.com"
			OR wu.user_email LIKE "%energy%"
			OR wu.user_email LIKE "%.fans"
			OR wu.user_email LIKE "%cake%"
			OR wu.user_email LIKE "%windowslive.com"
			OR wu.user_email LIKE "%videox%"
			OR wu.user_email LIKE "%prevent%"
			OR wu.user_email LIKE "%book.com"
			OR wu.user_email LIKE "%.cc"
			OR wu.user_email LIKE "%spam%"
			OR wu.user_email LIKE "%.gy"
			OR wu.user_email LIKE "%ford.com"
			OR wu.user_email LIKE "%brook%"
			OR wu.user_email LIKE "%brown%"
			OR wu.user_email LIKE "%griffith%"
			OR wu.user_email LIKE "%fastmail%"
			OR wu.user_email LIKE "%.money"
			OR wu.user_email LIKE "%.com3"
			OR wu.user_email LIKE "%minerals%"
			OR wu.user_email LIKE "%.cl"
			OR wu.user_email LIKE "%registrar%"
			OR wu.user_email LIKE "%abuse%"
			OR wu.user_email LIKE "%.bar"
			OR wu.user_email LIKE "%sport%"
			OR wu.user_email LIKE "%alabama%"
			OR wu.user_email LIKE "%images.%"
			OR wu.user_email LIKE "%brothers.com"
			OR wu.user_email LIKE "%fitness%"
			OR wu.user_email LIKE "%food%"
			OR wu.user_email LIKE "%bedroom%"
			OR wu.user_email LIKE "%christopher%"
			OR wu.user_email LIKE "%partners%"
			OR wu.user_email LIKE "%chuck%"
			OR wu.user_email LIKE "%rose%"
			OR wu.user_email LIKE "%cindy%"
			OR wu.user_email LIKE "%city%"
			OR wu.user_email LIKE "%middle%"
			OR wu.user_email LIKE "%provider%"
			OR wu.user_email LIKE "%travel%"
			OR wu.user_email LIKE "%construction%"
			OR wu.user_email LIKE "%shaw%"
			OR wu.user_email LIKE "%truck%"
			OR wu.user_email LIKE "%coach%"
			OR wu.user_email LIKE "%cody%"
			OR wu.user_email LIKE "%colby%"
			OR wu.user_email LIKE "%colin%"
			OR wu.user_email LIKE "%colleen%"
			OR wu.user_email LIKE "%education%"
			OR wu.user_email LIKE "%ariel%"
			OR wu.user_email LIKE "test%"
			OR wu.user_email LIKE "test-%"
			OR wu.display_name LIKE "%www%"
			OR wu.display_name LIKE "%aynard%"
			OR wu.display_name LIKE "%alters%"
			OR wu.display_name LIKE "%ordan%"
			OR wu.display_name LIKE "%lynn%"
			OR wu.display_name LIKE "%rry%"
			OR wu.display_name LIKE "%lly%"
			OR wu.display_name LIKE "%Cow%"
			OR wu.display_name LIKE "%urel %"
			OR wu.display_name LIKE "%ary%"
			OR wu.display_name LIKE "%rin %"
			OR wu.display_name LIKE "%ey %"
			OR wu.display_name LIKE "%ins%"
			OR wu.display_name LIKE "%ayne%"
			OR wu.display_name LIKE "%son%"
			OR wu.display_name LIKE "%lee%"
			OR wu.display_name LIKE "%sky%"
			OR wu.display_name LIKE "%issa %"
			OR wu.display_name LIKE "%ton %"
			OR wu.display_name LIKE "%der %"
			OR wu.display_name LIKE "%ers %"
			OR wu.display_name LIKE "%ert %"
			OR wu.display_name LIKE "%ber %"
			OR wu.display_name LIKE "%wan %"
			OR wu.display_name LIKE "%sh %"
			OR wu.display_name LIKE "%ott %"
			OR wu.display_name LIKE "%ary %"
			OR wu.display_name LIKE "%oug%"
			OR wu.user_email LIKE "%insbestusa%"
			OR wu.display_name LIKE "%yla%"
			OR wu.display_name LIKE "%ings %"
			OR wu.display_name LIKE "%ort %"
			OR wu.display_name LIKE "%ard %"
			OR wu.display_name LIKE "%oyd %"
			OR wu.display_name LIKE "%tch %"
			OR wu.display_name LIKE "%arles%"
			OR wu.display_name LIKE "%ogue%"
			OR wu.display_name LIKE "%ley%"
			OR wu.display_name LIKE "%Lucero%"
			OR wu.display_name LIKE "%Wu"
			OR wu.display_name LIKE "% Li%"
			OR wu.display_name LIKE "%ystal%"
			OR wu.display_name LIKE "%Finnegan%"
			OR wu.display_name LIKE "%illarreal%"
			OR wu.display_name LIKE "%oracio%"
			OR wu.display_name LIKE "%orace%"
			OR wu.display_name LIKE "%avenport%"
			OR wu.display_name LIKE "%krista%"
			OR wu.display_name LIKE "%krysta%"
			OR wu.display_name LIKE "%well "
			OR wu.display_name LIKE "%yant"
			OR wu.display_name LIKE "%ndependent"
			OR wu.display_name LIKE "%mazon%"
			OR wu.display_name LIKE "%IllurgE%"
			OR wu.display_name LIKE "%oosy"
			OR wu.display_name LIKE "%nny%"
			OR wu.display_name LIKE "%hola"
			OR wu.display_name LIKE "%jbw%"
			OR wu.display_name LIKE "%espresso%"
			OR wu.display_name LIKE "%agner%"
			OR wu.display_name LIKE "%arny%"
			OR wu.user_email LIKE "%mvrht%"
			OR wu.user_email LIKE "%.directory%"
			OR wu.user_email LIKE "%skechers.com"
			OR wu.user_email LIKE "%hotmails.com"
			OR wu.user_email LIKE "%cyprus%"
			OR wu.user_email LIKE "%bourns%"
			OR wu.user_email LIKE "%.su"
			OR wu.user_email LIKE "%.fun"
			OR wu.user_email LIKE "%revalt%"
			OR wu.user_email LIKE "%.gt"
			OR wu.user_email LIKE "%.au"
			OR wu.user_email LIKE "%whiteoaktherapy.com"
			OR wu.user_email LIKE "%unions.com"
			OR wu.user_email LIKE "%most-wanted-stuff.com"
			OR wu.user_email LIKE "%loan%"
			OR wu.user_email LIKE "%tiedercontrols.com"
			OR wu.user_email LIKE "%stelron.com"
			OR wu.user_email LIKE "%polarice.com"
			OR wu.user_email LIKE "%nurser%"
			OR wu.user_email LIKE "%onsite-hr.com"
			OR wu.user_email LIKE "%unions.com"
			OR wu.user_email LIKE "%greenssolicitors.com"
			OR wu.user_email LIKE "%rangeline%"
			OR wu.user_email LIKE "%owt%"
			OR wu.user_email LIKE "%packag%"
			OR wu.user_email LIKE "%trish%"
			OR wu.user_email LIKE "%burk%"
			OR wu.user_email LIKE "%healey%"
			OR wu.user_email LIKE "%mortgage%"
			OR wu.user_email LIKE "%sales%"
			OR wu.user_email LIKE "%pitts%"
			OR wu.user_email LIKE "%spenc%"
			OR wu.user_email LIKE "%.ga%"
			OR wu.user_email LIKE "%thai%"
			OR wu.user_email LIKE "%resort%"
			OR wu.user_email LIKE "%billing%"
			OR wu.user_email LIKE "%ndia%"
			OR wu.user_email LIKE "%yvo%"
			OR wu.user_email LIKE "%hir%"
			OR wu.user_email LIKE "%grl%"
			OR wu.user_email LIKE "%mcq%"
			OR wu.user_email LIKE "%jeffer%"
			OR wu.user_email LIKE "%baseball%"
			OR wu.user_email LIKE "%publish%"
			OR wu.user_email LIKE "%viral%"
			OR wu.user_email LIKE "%americ%"
			OR wu.user_email LIKE "%steve%"
			OR wu.user_email LIKE "%itch%"
			OR wu.user_email LIKE "%ela%"
			OR wu.user_email LIKE "%click%"
			OR wu.user_email LIKE "%body%"
			OR wu.user_email LIKE "%martinez%"
			OR wu.user_email LIKE "%contract%"
			OR wu.user_email LIKE "%embleton%"
			OR wu.user_email LIKE "%oole%"
			OR wu.user_email LIKE "%bulgaria%"
			OR wu.user_email LIKE "%@alihkan.com"
			OR wu.user_email LIKE "%pavestone.com"
			OR wu.user_email LIKE "%.ro"
			OR wu.user_email LIKE "%management%"
			OR wu.user_email LIKE "%board%"
			OR wu.user_email LIKE "%booking%"
			OR wu.user_email LIKE "%jorg%"
			OR wu.user_email LIKE "%kev%"
			OR wu.user_email LIKE "%orff%"
			OR wu.user_email LIKE "%grew%"
			OR wu.user_email LIKE "%paul%"
			OR wu.user_email LIKE "%baltimore%"
			OR wu.user_email LIKE "%plastic%"
			OR wu.user_email LIKE "%hilda%"
			OR wu.user_email LIKE "%bean%"
			OR wu.user_email LIKE "%countryclub%"
			OR wu.user_email LIKE "%enj%"
			OR wu.user_email LIKE "%.us"
			OR wu.user_email LIKE "%outlet%"
			OR wu.user_email LIKE "%oateng%"
			OR wu.user_email LIKE "%guez%"
			OR wu.user_email LIKE "%purchas%"
			OR wu.user_email LIKE "%farms%"
			OR wu.user_email LIKE "%ynn%"
			OR wu.user_email LIKE "%.jp"
			OR wu.user_email LIKE "%alan%"
			OR wu.user_email LIKE "%have%"
			OR wu.user_email LIKE "%issa%"
			OR wu.user_email LIKE "%tracie%"
			OR wu.user_email LIKE "%tracy%"
			OR wu.user_email LIKE "%smith%"
			OR wu.user_email LIKE "%anne%"
			OR wu.user_email LIKE "%nguyen%"
			OR wu.user_email LIKE "%florist%"
			OR wu.user_email LIKE "%helen%"
			OR wu.user_email LIKE "%beatriz%"
			OR wu.user_email LIKE "%dustin%"
			OR wu.user_email LIKE "%paint%"
			OR wu.user_email LIKE "%acme%"
			OR wu.user_email LIKE "%.netscape"
			OR wu.user_email LIKE "%sina.com"
			OR wu.user_email LIKE "sales%"
			OR wu.user_email LIKE "%ny.%"
			OR wu.user_email LIKE "%nyc.%"
			OR wu.user_email LIKE "%ebon%"
			OR wu.user_email LIKE "%thomp%"
			OR wu.user_email LIKE "%industr%"
			OR wu.user_email LIKE "%pharm%"
			OR wu.user_email LIKE "%deligh%"
			OR wu.user_email LIKE "%mcd%"
			OR wu.user_email LIKE "%mcf%"
			OR wu.user_email LIKE "%yong%"
			OR wu.user_email LIKE "%connect%"
			OR wu.user_email LIKE "%ryan%"
			OR wu.user_email LIKE "%sarah%"
			OR wu.user_email LIKE "%mindspring%"
			OR wu.user_email LIKE "%shan%"
			OR wu.user_email LIKE "%lesl%"
			OR wu.user_email LIKE "%kath%"
			OR wu.user_email LIKE "%jud%"
			OR wu.user_email LIKE "%sny%"
			OR wu.user_email LIKE "%shep%"
			OR wu.user_email LIKE "%wot%"
			OR wu.user_email LIKE "%scarbour%"
			OR wu.user_email LIKE "%majority%"
			OR wu.display_name LIKE "%spence%"
			OR wu.display_name LIKE "%keat%"
			OR wu.display_name LIKE "%jho%"
			OR wu.display_name LIKE "%yw%"
			OR wu.display_name LIKE "%lyn%"
			OR wu.display_name LIKE "%mcc%"
			OR wu.display_name LIKE "%ovski%"
			OR wu.display_name LIKE "%stockcentro%"
			OR wu.display_name LIKE "%erly%"
			OR wu.display_name LIKE "%itchen%"
			OR wu.display_name LIKE "%ramon%"
			OR wu.display_name LIKE "%beck%"
			OR wu.display_name LIKE "%chap%"
			OR wu.display_name LIKE "%morales%"
			OR wu.display_name LIKE "%puttn%"
			OR wu.display_name LIKE "%brady%"
			OR wu.display_name LIKE "%estelle%"
			OR wu.display_name LIKE "%win%"
			OR wu.display_name LIKE "%chang%"
			OR wu.display_name LIKE "%melody%"
			OR wu.display_name LIKE "%wan%"
			OR wu.display_name LIKE "%steph%"
			OR wu.display_name LIKE "%ilw%"
			OR wu.display_name LIKE "%acy%"
			OR wu.display_name LIKE "%ght%"
			OR wu.display_name LIKE "%lton%"
			OR wu.display_name LIKE "%ower%"
			OR wu.display_name LIKE "%sye%"
			OR wu.display_name LIKE "%bak%"
			OR wu.display_name LIKE "%chad%"
			OR wu.display_name LIKE "%john%"
			OR wu.display_name LIKE "%ight%"
			OR wu.display_name LIKE "%whit%"
			OR wu.display_name LIKE "%remium%"
			OR wu.display_name LIKE "%avage%"
			OR wu.display_name LIKE "%usiness%"
			OR wu.display_name LIKE "%investor%"
			OR wu.display_name LIKE "%tester%"
			OR wu.user_email LIKE "%testiamo%"
			OR wu.user_email LIKE "%test-blocca%"
			OR wu.user_email REGEXP 'test[0-9]{1,2}'
			OR wu.user_email REGEXP 'test-[0-9]{1,2}'
			OR wu.user_email REGEXP '^[a-zA-Z0-9._%+-]{1,3}@'
			OR wu.user_email REGEXP '^[^.]+(\\.[^.]+){3,}@'
			OR wu.user_email REGEXP '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$'
    )
))
ORDER BY wu.ID ASC
